config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  get '/about', to: 'lists#about'
  resources :lists, only: %i[index new show create] do
    resources :bookmarks, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # GET request
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  # POST request
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render '/lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.select { |b| b.movie_id == params[:id].to_i && b.list_id == params[:list_id].to_i }
    @bookmark[0].destroy
    redirect_to list_path(params[:list_id]), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def about() end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light">
      <div class="container-fluid">
        <a href="/">
          <div class="navbar-brand"></div>
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/lists">My Lists</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/lists/new">New List</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
    <div class="container">
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="/" class="nav-link px-3 text-muted">Home</a></li>
          <li class="nav-item"><a href="/lists/new" class="nav-link px-3 text-muted">New List</a></li>
          <li class="nav-item"><a href="/about" class="nav-link px-3 text-muted">About</a></li>
        </ul>
       <p class="text-center text-muted"> <i class="fa-solid fa-code"></i> First, solve the problem. Then, write the code. <i class="fa-solid fa-code"></i></p>
      </footer>
    </div>
  </body>
</html>

app/views/lists/about.html.erb
<div class="banner-about">
  <h1>Here you can find more information about future updates!</h1>
</div>

app/views/lists/index.html.erb
<div class="banner-index">
  <h1>Save any kind of movies</h1>
</div>
<div class="container-index">
  <div class="d-flex justify-content-between">
    <div class="p-2">
      <h2>My Lists</h2>
    </div>
    <div class="newList-index">
      <a class="btn btn-success newMovie" href="/lists/new">Create a movie list</a>
    </div>
  </div>
  <div class="row mb-2">
    <% @lists.each do |list| %>
      <div class="col-3 p-3">
        <div class="col-12 card card-index justify-content-center align-items-center" style="background-image: linear-gradient(to top, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.7) 60%, rgba(0, 0, 0, 0.8) 100%), url('<%= list.photo.attached? ? (cl_image_path list.photo.key) : ('https://res.cloudinary.com/djs8vtzox/image/upload/v1662092387/development/default_list_image_x7fm8z.webp')  %>')">
          <%= link_to "#{list.name}", "/lists/#{list.id}", class: 'listItems-index'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner-new">
  <h1>Create a new List!</h1>
</div>
<div class="container">
  <div class="form-new mb-3 p-5">
  <h4>Details -</h4>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, :class =>"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(to top, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.7) 60%, rgba(0, 0, 0, 0.8) 100%), url('<%= @list.photo.key ? (cl_image_path @list.photo.key) : (cl_image_path 'https://res.cloudinary.com/djs8vtzox/image/upload/v1662104768/production/default_list_image_jwxs6x.webp') %>'">
  <h1><%= @list.name %></h1>
</div>
<div class="container-show">
  <div class="d-flex justify-content-end">
    <div class="newList">
      <a class="btn btn-success p-2" data-bs-toggle="collapse" href="#collapseExample" role="button"
      aria-expanded="false" aria-controls="collapseExample">
        Add a movie
      </a>
    </div>
  </div>
  <div class="collapse collapse-show" id="collapseExample">
    <div class="card card-body">
      <div class="card-title"><strong>Add Movie  to <%= @list.name %></strong></div>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.button :submit, :class =>"btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="d-flex">
    <% @list.movies.each do |movie| %>
      <div class="card m-2 card-show" style="width: 18rem;">
        <img class="card-img-top" src="<%= movie.poster_url %>" alt="Movie Image">
        <div class="card-body">
          <h5 class="card-title"><%= movie.title %></h5>
          <p class="card-text"><%= movie.overview %></p>
        </div>
        <div class="d-flex justify-content-between p-3">
          <div class="flex-item">
            <p class="card-text">⭐ <%= movie.rating %></p>
          </div>
          <div class="flex-item">
            <%= link_to "Delete", list_bookmark_path(@list, movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{movie.title}?"} %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>